############################################################
#        RPP Manuscript Figure 1,2,3 (+ demonstrations)    #
#                                                          #
# Created by Fred Hasselman on behalf of the RPP intiative #
############################################################

# All the functions that are required to recreate the Figures are available in a GitHub sourceable file: `C3PR.R` 

############################################################
# C-3PR: Evaluating Scientific *C*laims: *P*ost *P*ublication *P*eer *R*eview, *R*eplication and *R*eproduction.
#
# An R function library created in the contex of analysing and visualising data generated by several Open Science intiatives.
# 
# C-3PR Created by [Fred Hasselman](http://fredhasselman.com) on behalf of the ManyLabs1, ManyLabs2, RPP and Curate Science projects
############################################################


# SETUP -------------------------------------------------------------------

# Use this code (from the devtools package) to source C-3PR directly from GitHub:
require(devtools)
source_url('https://raw.githubusercontent.com/FredHasselman/toolboxR/master/C-3PR.R')

# This will load and (if necessary) install libraries frequently used for data management and plotting
# If you want to load only the libraries used in this file, uncomment the following line:
# in.IT(c('dplyr','plyr','ggplot2','RColorbrewer','scales','lattice','gridExtra'))
in.PLOT()
in.IO()

#RPPdata <- read.csv2(textConnection(getURL('https://raw.githubusercontent.com/chartgerink/rpp/master/Copy%20of%20tilburg%20data%2037%20final.csv')),stringsAsFactors=F, fill = T, header=T, fileEncoding='latin-1')

RPPdata <- read.csv("rpp_data.csv",stringsAsFactors=F)
RPPdata <- df.Clean(RPPdata)$df
RPPdata <- filter(RPPdata, !is.na(T.pval.USE.O)&!is.na(T.pval.USE.R))
nrow(RPPdata)

idOK <- complete.cases(RPPdata$T.r.O,RPPdata$T.r.R)
sum(idOK)

## Choose from these for a colorblind friendly pallette
# display.brewer.all()
# mypalette <- brewer.pal(5,"Set2")
# palette(mypalette)

# ggplot themes in C-3PR
mytheme <- gg.theme("clean")

# VIOLIN QUANTILE PLOTS (VQP) -----------------------------------------------

# Restructure the data to "long" format: Study type will be a factor
df <- dplyr::select(RPPdata,starts_with("T."))
df <- data.frame(EffectSize=c(df$T.r.O,df$T.r.R),p.value=c(df$T.pval.USE.O,df$T.pval.USE.R),grp=factor(c(rep("Original Studies",times=length(df$T.r.O)),rep("Replications",times=length(df$T.r.R)))))
df$grpN    <- as.numeric(df$grp)
df$p.value <- as.numeric(df$p.value)
df$sig <- 0
df$sig[df$p.value<.05] <- 1
# Numbers refer to plot markers
df$pch <- 25
df$pch[df$p.value<.05] <- 21
df$sigf <- "Not significant"
df$sigf[df$p.value<.05] <- "Sinificant"
df$sigf <- factor(df$sigf)

# VQP PANEL A: p-value -------------------------------------------------
probs=seq(0,1,.25)
# Get quantiles and frequencies from data
qtiles <- ldply(unique(df$grpN),function(gr) quantile(round(df$p.value[df$grpN==gr],digits=4),probs,na.rm=T,type=3))
freqs  <- ldply(unique(df$grpN),function(gr) table(cut(df$p.value[df$grpN==gr],breaks=qtiles[gr,],na.rm=T,include.lowest=T,right=T)))
labels <- sapply(unique(df$grpN),function(gr)levels(cut(round(df$p.value[df$grpN==gr],digits=4), breaks = qtiles[gr,],na.rm=T,include.lowest=T,right=T)))

# Get regular ggplot violin
g.pv <- ggplot(df,aes(x=grp,y=p.value)) + geom_violin(aes(group=grp),scale="width",color="grey30",fill="grey30",trim=T,adjust=.7)
# Cut at quantiles
g.pv0 <- vioQtile(g.pv,qtiles,probs)
# Garnish 
g.pv1 <- g.pv0 + geom_hline(aes(yintercept=.05),linetype=2) + ggtitle("A") + xlab("") + ylab("p-value") + 
  gg.theme("clean") 

# Save
ggsave("RPP_pv.eps",plot=g.pv1)
g.pv1

# VQP PANEL B: effect size -------------------------------------------------
qtiles <- ldply(unique(df$grpN),function(gr) quantile(df$EffectSize[df$grpN==gr],probs,na.rm=T,type=3,include.lowest=T))
freqs  <- ldply(unique(df$grpN),function(gr) table(cut(df$EffectSize[df$grpN==gr],breaks=qtiles[gr,],na.rm=T,include.lowest=T)))
# build the base violins
g.es  <- ggplot(df,aes(x=grp,y=EffectSize)) + geom_violin(aes(group=grpN),scale="width",fill="grey40",color="grey40",trim=T,adjust=.7) 
# Get the quantiles
g.es0 <- vioQtile(g.es,qtiles=qtiles,probs=probs) 
# Garnish
g.es1 <- g.es0 + ggtitle("B") + xlab("") + ylab("Effect Size") + scale_y_continuous(breaks=c(0,.25,.5,.75,1),limits=c(-.5,1)) + mytheme 
# Save 
ggsave("RPP_ES.eps",plot=g.es1)
g.es1

# Combine plots [if this does not work just use RStudio to export]
pdf("RPP_vioQtileTST.pdf",pagecentre=T, width=20,height=8 ,paper = "special")
multi.PLOT(g.pv1,g.es1,cols=2)
dev.off()

# P-VALUE PLOTS -----------------------------------------------------------

# One of many ways to manipulate positions of multiple plots in one output device
vpM <- viewport(width = 0.6, height = 0.6, x=0.4, y=.7)
vpZ <- viewport(width = 0.6, height = 0.3, x=.4, y=.25)
grid.show.viewport(vpZ)
# This will position a ggplot "main" and "sub" in their respective slots
full <- function() {
     print(main,vp = vpM)
     print(sub, vp = vpZ)
 }

mypalette        <- brewer.pal(9,"YlOrRd")
RPPdata$Power.Rn <- as.numeric(RPPdata$Power.R)

# Scatter with size=power.replication --------------------------------------------------
main <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R))+ 
  scale_x_continuous(breaks=c(0,.01,.05),limits=c(0,.07)) + 
  ggtitle("") + xlab("Original Study p-value") + ylab("Replication p-value") + 
  scale_size_continuous(name="Replication:\nPower",breaks=seq(0,1,length=11))  + ylim(c(0,1.1)) + 
  geom_vline(aes(xintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_hline(aes(yintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_point(aes(size=Power.Rn),alpha=.8) + mytheme
 
ggsave("RPP_pv_Main0.png",plot=main)

sub <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R)) + 
  geom_vline(aes(xintercept=0.05),linetype=2,color=mypalette[9]) +
  geom_hline(aes(yintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_point(aes(size=Power.Rn),alpha=.8) + 
  scale_x_continuous(breaks=c(0,.001,.005),limits=c(0,.005)) + 
  ggtitle("0 < p < 0.005") + 
  xlab("")+ ylab("") + 
  scale_size_continuous(guide=F) +
  ylim(c(0,1))  + mytheme

ggsave("RPP_pv_sub0.png",plot=sub)

# Compine plots [if this does not work use RStudio Export wizard]
pdf("RPP_pvalues0.pdf",pagecentre=T, width=15,height=8 ,paper = "special")
full()
dev.off()

# Scatter with size=power.replication and journal --------------------------------------------------
main <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R))+ 
  scale_x_continuous(breaks=c(0,.01,.05),limits=c(0,.06)) + 
  ggtitle("") + xlab("Original Study p-value") + ylab("Replication p-value") + 
  scale_color_brewer(name="Journal",palette="Set2") + 
  scale_size_continuous(name="Replication:\nPower",breaks=seq(0,1,length=11))  + ylim(c(0,1)) + 
  geom_vline(aes(xintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_hline(aes(yintercept=0.05),linetype=2,color=mypalette[9]) + 
#   geom_vline(aes(xintercept=0.0),linetype=1,color="grey60") + 
#   geom_vline(aes(xintercept=0.005),linetype=1,color="grey60") + 
  geom_point(aes(size=Power.Rn,color=Journal.O),alpha=.8) + mytheme
 
ggsave("RPP_pv_Main1.png",plot=main)


sub <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R)) + 
  geom_vline(aes(xintercept=0.05),linetype=2,color=mypalette[9]) +
  geom_hline(aes(yintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_point(aes(size=Power.Rn,color=Journal.O),alpha=.8) + 
  scale_x_continuous(breaks=c(0,.001,.005),limits=c(0,.005)) + 
  #ggtitle("0 < p < 0.005") + 
  xlab("")+ ylab("") + 
  scale_size_continuous(guide=F) +
  scale_color_brewer(palette="Set2",guide=F) +
  ylim(c(0,1))  + mytheme

pdf("RPP_pvalues1.pdf",pagecentre=T, width=15,height=8 ,paper = "special")
full()
dev.off()
ggsave("RPP_pv_sub1.png",plot=sub)

# Scatter with size=power.replication + ES color --------------------------------------------------
main <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R)) + 
  geom_vline(aes(xintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_hline(aes(yintercept=0.05),linetype=2,color=mypalette[9]) +
  geom_point(aes(size=Power.Rn,color=T.r.O),alpha=.8) +
  scale_x_continuous(breaks=c(0,.01,.05),limits=c(0,.07)) +
  scale_size_continuous(name="Replication:\nPower",breaks=seq(0,1,length=11)) + 
  scale_color_gradient(name="Original Study:\nEffect Size",low=mypalette[1],high=mypalette[9],breaks=c(0,0.1,0.3,0.5,.8)) +
  ggtitle("") + xlab("Original Study p-value") + ylab("Replication p-value") + ylim(c(0,1)) + 
  mytheme

ggsave("RPP_pv_main2.png",plot=main)
 
sub <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R)) + 
  geom_point(aes(size=Power.Rn,color=T.r.O),alpha=.8) + 
  scale_x_continuous(breaks=c(0,.001,.005),limits=c(0,.005)) + 
  ggtitle("0 < p < 0.005") + xlab("") + ylab("") + 
  scale_size_continuous(name="",guide=F) + 
  scale_color_gradient(name="",low=mypalette[1],high=mypalette[9],breaks=c(0,0.1,0.3,0.5,.8),guide=F)+
  ylim(c(0,1))  + mytheme

ggsave("RPP_pv_sub2.png",plot=sub)


pdf("RPP_pvalues2.pdf",pagecentre=T, width=15,height=8 ,paper = "special")
full()
dev.off()


# EFFECT SIZE PLOTS -------------------------------------------------------------
RPPdata$oriSig <- "Significant"
RPPdata$oriSig[RPPdata$T.pval.USE.O>=.05] <- "Not Significant"
RPPdata$oriSig <- factor(RPPdata$oriSig)

RPPdata$repSig <- "Significant"
RPPdata$repSig[RPPdata$T.pval.USE.R>=.05] <- "Not Significant"
RPPdata$repSig <- factor(RPPdata$repSig)

RPPdata$repSig <- factor(RPPdata$repSig)

# Scatter with density margin plots
blankPlot<-plotHolder()
xDense <- ggplot(RPPdata, aes(x=T.r.O, fill=oriSig)) + geom_density(aes(y= ..count..),trim=F,alpha=.5) + xlab("") + ylab("") +  xlim(0,1) +
  gg.theme("noax") + theme(legend.position = "none",plot.margin = unit(c(0,0,0,4), "lines"))
yDense <- ggplot(RPPdata, aes(x=T.r.R, fill=repSig)) + 
  geom_density(aes(y= ..count..),trim=F,alpha=.5) + xlab("") + ylab("") + xlim(-.5,1) + coord_flip() + 
  gg.theme("noax") + theme(legend.position = "none", plot.margin = unit(c(0,0,3,0), "lines")) 

scatterP<-
  ggplot(RPPdata,aes(x=T.r.O,y=T.r.R)) +  
  geom_hline(aes(yintercept=0),linetype=2) +
  geom_abline(intercept=0,slope=1,color="Grey60")+
  geom_point(aes(size=Power.Rn,fill=repSig),color="grey30",shape=21,alpha=.8) + 
  geom_rug(aes(color=oriSig),size=1,sides="b",alpha=.6) + 
  geom_rug(aes(color=repSig),,size=1,sides="l",alpha=.6) + 
  scale_x_continuous(name="Original Effect Size",limits=c(0,1),breaks=c(0,.25,.5,.75,1)) + 
  scale_y_continuous(name="Replication Effect Size",limits=c(-.5,1),breaks=c(-.5,-.25,0,.25,.5,.75,1)) + 
  ggtitle("") + xlab("") + ylab("") + 
  scale_size_continuous(name="Replication Power",range=c(2,9)) + 
  scale_color_discrete(name="Replication p-value") +
  scale_fill_discrete(name="Replication p-value") +
  gg.theme("clean") + theme(legend.position=c(.9,.6), plot.margin = unit(c(-2,-1.5,2,2), "lines")) 
  

pdf("RPP_ES_density.pdf",pagecentre=T, width=15,height=12 ,paper = "special")
grid.arrange(xDense, blankPlot, scatterP, yDense, ncol=2, nrow=2, widths=c(4, 1.4), heights=c(1.4, 4))
dev.off()


# Scatter with rug B L
rm(scatterP)
scatterP<-
  ggplot(RPPdata,aes(x=T.r.O,y=T.r.R)) +  
  geom_hline(aes(yintercept=0),linetype=2) +
  geom_abline(intercept=0,slope=1,color="Grey60")+
  geom_point(aes(size=Power.Rn,fill=repSig),color="grey30",shape=21,alpha=.8) + 
  geom_rug(aes(color=oriSig),size=1,sides="b",alpha=.6) + 
  geom_rug(aes(color=repSig),,size=1,sides="l",alpha=.6) + 
  scale_x_continuous(name="Original Effect Size",limits=c(0,1)) + 
  scale_y_continuous(name="Replication Effect Size",limits=c(-.5,1)) + 
  ggtitle("") + xlab("") + ylab("") + 
  scale_size_continuous(name="Replication Power",range=c(2,9)) + 
  scale_color_discrete(name="Replication p-value") +
  scale_fill_discrete(name="Replication p-value") +
  gg.theme("clean")
  

pdf("RPP_ES_density_bl.pdf",pagecentre=T, width=10,height=15 ,paper = "special")
scatterP
dev.off()

# Scatter with rug T R
rm(scatterP)
scatterP<-
  ggplot(RPPdata,aes(x=T.r.O,y=T.r.R)) +  
  geom_hline(aes(yintercept=0),linetype=2) +
  geom_abline(intercept=0,slope=1,color="Grey60")+
  geom_point(aes(size=Power.Rn,fill=repSig),color="grey30",shape=21,alpha=.8) + 
  geom_rug(aes(color=oriSig),size=1,sides="t",alpha=.6) + 
  geom_rug(aes(color=repSig),,size=1,sides="r",alpha=.6) + 
  scale_x_continuous(name="Original Effect Size",limits=c(0,1)) + 
  scale_y_continuous(name="Replication Effect Size",limits=c(-.5,1)) + 
  ggtitle("") + xlab("") + ylab("") + 
  scale_size_continuous(name="Replication Power",range=c(2,9)) + 
  scale_color_discrete(name="Replication p-value") +
  scale_fill_discrete(name="Replication p-value") +
  gg.theme("clean")
  

pdf("RPP_ES_density_tr.pdf",pagecentre=T, width=15,height=12 ,paper = "special")
scatterP
dev.off()
