############################################################
#        RPP Manuscript Figure 1,2,3                       #
#                                                          #
# Created by Fred Hasselman on behalf of the RPP intiative #
############################################################

# All the custom functions that are required to recreate the Figures are available in a GitHub sourceable file: `C-3PR.R` 
# It is available here: https://github.com/FredHasselman/toolboxR

############################################################
# C-3PR: Evaluating Scientific *C*laims: *P*ost *P*ublication *P*eer *R*eview, *R*eplication and *R*eproduction.
#
# An R function library created in the contex of analysing and visualising data generated by several Open Science intiatives.
# 
# C-3PR Created by [Fred Hasselman](https://osf.io/ujgs6/) on behalf of the ManyLabs1, ManyLabs2, RPP and Curate Science projects
############################################################


# SETUP local R-------------------------------------------------------------------

# Use this code (from the devtools package) to source C-3PR directly from GitHub:
require(devtools)
source_url('https://raw.githubusercontent.com/FredHasselman/toolboxR/master/C-3PR.R')

# This will load and (if necessary) install libraries frequently used for data management and plotting
in.IT(c('ggplot2','RColorBrewer','lattice','gridExtra','plyr','dplyr','httr'))

# Read the data from the OSF storage
# Note: get.OSFfile() returns a list with the Excel data (df) and information (info) containing the URL download timestamp and original column and rownames (these names will be changed if dfCln=TRUE).  
RPPdata <- get.OSFfile(code='https://osf.io/5wup8/',dfCln=T)$df

# Select the completed replication studies
RPPdata <- dplyr::filter(RPPdata, !is.na(T.pval.USE.O),!is.na(T.pval.USE.R))
# We have 99 studies for which p-values and effect sizes could be calculated
nrow(RPPdata)
# We have 97 studies for which p-values of the original effect were significantly below .05
idOK <- complete.cases(RPPdata$T.r.O,RPPdata$T.r.R)
sum(idOK)

# Get ggplot2 themes predefined in C-3PR
mytheme <- gg.theme("clean")

############
# FIGURE 1
# VIOLIN QUANTILE PLOTS (VQP) -----------------------------------------------
############

# Restructure the data to "long" format: Study type will be a factor
df <- dplyr::select(RPPdata,starts_with("T."))
df <- data.frame(EffectSize=as.numeric(c(df$T.r.O,df$T.r.R)),p.value=as.numeric(c(df$T.pval.USE.O,df$T.pval.USE.R)),grp=factor(c(rep("Original Studies",times=length(df$T.r.O)),rep("Replications",times=length(df$T.r.R)))))

# Create some variables for plotting
df$grpN <- as.numeric(df$grp)
probs   <- seq(0,1,.25)

# VQP PANEL A: p-value -------------------------------------------------

# Get p-value quantiles and frequencies from data
qtiles <- ldply(unique(df$grpN),function(gr) quantile(round(df$p.value[df$grpN==gr],digits=4),probs,na.rm=T,type=3))
freqs  <- ldply(unique(df$grpN),function(gr) table(cut(df$p.value[df$grpN==gr],breaks=qtiles[gr,],na.rm=T,include.lowest=T,right=T)))
labels <- sapply(unique(df$grpN),function(gr)levels(cut(round(df$p.value[df$grpN==gr],digits=4), breaks = qtiles[gr,],na.rm=T,include.lowest=T,right=T)))

# Check the Quantile bins!
ori           <-cbind(freq=as.numeric(t(freqs[1,])))
rownames(ori) <- labels[,1]
ori

rep           <-cbind(freq=as.numeric(t(freqs[2,])))
rownames(rep) <- labels[,2]
rep

# Get regular violinplot using package ggplot2
g.pv <- ggplot(df,aes(x=grp,y=p.value)) + geom_violin(aes(group=grp),scale="width",color="grey30",fill="grey30",trim=T,adjust=.7)
# Cut at quantiles using vioQtile() in C-3PR
g.pv0 <- vioQtile(g.pv,qtiles,probs)
# Garnish 
g.pv1 <- g.pv0 + geom_hline(aes(yintercept=.05),linetype=2) + 
  ggtitle("A") + xlab("") + ylab("p-value") + 
  mytheme
# View
g.pv1

## Uncomment to save panel A as a seperate file
# ggsave("RPP_F1_VQPpv.eps",plot=g.pv1)

# VQP PANEL B: effect size -------------------------------------------------

# Get effect size quantiles and frequencies from data
qtiles <- ldply(unique(df$grpN),function(gr) quantile(df$EffectSize[df$grpN==gr],probs,na.rm=T,type=3,include.lowest=T))
freqs  <- ldply(unique(df$grpN),function(gr) table(cut(df$EffectSize[df$grpN==gr],breaks=qtiles[gr,],na.rm=T,include.lowest=T)))
labels <- sapply(unique(df$grpN),function(gr)levels(cut(round(df$EffectSize[df$grpN==gr],digits=4), breaks = qtiles[gr,],na.rm=T,include.lowest=T,right=T)))

# Check the Quantile bins!
ori           <-cbind(freq=as.numeric(t(freqs[1,])))
rownames(ori) <- labels[,1]
ori

rep           <-cbind(freq=as.numeric(t(freqs[2,])))
rownames(rep) <- labels[,2]
rep

# Get regular violinplot using package ggplot2
g.es  <- ggplot(df,aes(x=grp,y=EffectSize)) + geom_violin(aes(group=grpN),scale="width",fill="grey40",color="grey40",trim=T,adjust=1) 
# Cut at quantiles using vioQtile() in C-3PR
g.es0 <- vioQtile(g.es,qtiles=qtiles,probs=probs) 
# Garnish
g.es1 <- g.es0 + 
  ggtitle("B") + xlab("") + ylab("Effect Size") + 
  scale_y_continuous(breaks=c(-.25,-.5,0,.25,.5,.75,1),limits=c(-.5,1)) + mytheme 
# View
g.es1

# # Uncomment to save panel B as a seperate file
# ggsave("RPP_F1_VQPes.eps",plot=g.es1)

# VIEW panels in one plot using the multi.PLOT() function from C-3PR
multi.PLOT(g.pv1,g.es1,cols=2)

# SAVE combined plots as PDF
pdf("RPP_Figure1_vioQtile.pdf",pagecentre=T, width=20,height=8 ,paper = "special")
multi.PLOT(g.pv1,g.es1,cols=2)
dev.off()


########################
# FIGURE 2
# P-VALUE PLOTS -----------------------------------------------------------
########################

# One of many ways to manipulate positions of multiple plots in one output device
vpM <- viewport(width = 0.6, height = 0.6, x=0.4, y=.7)
vpZ <- viewport(width = 0.6, height = 0.3, x=.4, y=.25)
grid.show.viewport(vpZ)
# This will position a ggplot "main" and "sub" in their respective slots
full <- function() {
     plot.new()
     print(main,vp = vpM)
     print(sub, vp = vpZ)
 }

# Choose a palette from RColorBrewer
mypalette        <- brewer.pal(9,"YlOrRd")
# Get the Replication observed power
RPPdata$Power.Rn <- as.numeric(RPPdata$Power.R)

# Scatter with size=power.replication and journal --------------------------------------------------
main <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R))+ 
  scale_x_continuous(breaks=c(0,.01,.05),limits=c(0,.06)) + 
  ggtitle("") + xlab("Original Study p-value") + ylab("Replication p-value") + 
  scale_color_brewer(name="Journal",palette="Set2") + 
  scale_size_continuous(name="Replication:\nPower",breaks=seq(0,1,length=11))  + ylim(c(0,1)) + 
  geom_vline(aes(xintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_hline(aes(yintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_point(aes(size=Power.Rn,color=Journal.O),alpha=.8) + mytheme

## Uncomment to save subplot
# ggsave("RPP_F2_pvMain.png",plot=main)

sub <- ggplot(RPPdata,aes(x=T.pval.USE.O,y=T.pval.USE.R)) + 
  geom_vline(aes(xintercept=0.05),linetype=2,color=mypalette[9]) +
  geom_hline(aes(yintercept=0.05),linetype=2,color=mypalette[9]) + 
  geom_point(aes(size=Power.Rn,color=Journal.O),alpha=.8) + 
  scale_x_continuous(breaks=c(0,.001,.005),limits=c(0,.005)) + 
  ggtitle("0 < p < 0.005") + 
  xlab("")+ ylab("") + 
  scale_size_continuous(guide=F) +
  scale_color_brewer(palette="Set2",guide=F) +
  ylim(c(0,1)) + mytheme

## Uncomment to save subplot
# ggsave("RPP_F2_pvsub.png",plot=sub)

# VIEW combined plots
full()

# SAVE combined plots as PDF (note: the lines emphasizing the 'blow-up' figure in the publication were drawn in later using image editing software)
pdf("RPP_Figure2_pvalues.pdf",pagecentre=T, width=15,height=8 ,paper = "special")
full()
dev.off()


########################
# FIGURE 3
# EFFECT SIZE DENSITY PLOTS -------------------------------------------------------------
########################

# Setup some variables
RPPdata$oriSig <- "Not Significant"
# 3 studies claimed an effect at .05 < p < .06
RPPdata$oriSig[RPPdata$T.pval.USE.O<=.06] <- "Significant"
RPPdata$oriSig <- factor(RPPdata$oriSig)

RPPdata$repSig <- "Not Significant"
RPPdata$repSig[RPPdata$T.pval.USE.R<=.05] <- "Significant"
RPPdata$repSig <- factor(RPPdata$repSig)
RPPdata$repSig <- factor(RPPdata$repSig)

# Create a scatterplot with density margin plots

# The plotHolder() function from C-3PR creates a blank plot template that will hold the figures
blankPlot <- plotHolder()

# X margin density plot (note: gg.theme() from C-3PR can be used directly in a ggplot2() call)
xDense <- ggplot(RPPdata, aes(x=T.r.O, fill=oriSig)) + 
  geom_density(aes(y= ..count..),trim=F,alpha=.5) + 
  xlab("") + ylab("") + xlim(0,1) +
  gg.theme("noax") + 
  theme(legend.position = "none",plot.margin = unit(c(0,0,0,4), "lines"))

## Uncomment to save subplot
# ggsave("RPP_F3_xDense.png",plot=xDense)

# Y margin density plot (note: gg.theme() from C-3PR can be used directly in a ggplot2() call)
yDense <- ggplot(RPPdata, aes(x=T.r.R, fill=repSig)) + 
  geom_density(aes(y= ..count..),trim=F,alpha=.5) + 
  xlab("") + ylab("") + xlim(-.5,1) + 
  coord_flip() + 
  gg.theme("noax") + 
  theme(legend.position = "none", plot.margin = unit(c(0,0,3,0), "lines")) 

## Uncomment to save subplot
# ggsave("RPP_F3_yDense.png",plot=yDense)

# The main scatterplot (note: gg.theme() from C-3PR can be used directly in a ggplot2() call)
scatterP<-
  ggplot(RPPdata,aes(x=T.r.O,y=T.r.R)) +  
  geom_hline(aes(yintercept=0),linetype=2) +
  geom_abline(intercept=0,slope=1,color="Grey60")+
  geom_point(aes(size=Power.Rn,fill=repSig),color="Grey30",shape=21,alpha=.8) + 
  geom_rug(aes(color=oriSig),size=1,sides="b",alpha=.6) + 
  geom_rug(aes(color=repSig),,size=1,sides="l",alpha=.6) + 
  scale_x_continuous(name="Original Effect Size",limits=c(0,1),breaks=c(0,.25,.5,.75,1)) + 
  scale_y_continuous(name="Replication Effect Size",limits=c(-.5,1),breaks=c(-.5,-.25,0,.25,.5,.75,1)) + 
  ggtitle("") + xlab("") + ylab("") + 
  scale_size_continuous(name="Replication Power",range=c(2,9)) + 
  scale_color_discrete(name="p-value") +
  scale_fill_discrete(name="p-value") +
  gg.theme("clean") + 
  theme(legend.position=c(.9,.6), plot.margin = unit(c(-2,-1.5,2,2), "lines")) 

## Uncomment to save subplot
# ggsave("RPP_F3_scatter.png",plot=scatterP)

# Yet another way to organise plots: grid.arrange() from the gridExtra package.
grid.arrange(xDense, blankPlot, scatterP, yDense, ncol=2, nrow=2, widths=c(4, 1.4), heights=c(1.4, 4))

# SAVE combined plots as PDF
pdf("RPP_Figure3_ESdensity.pdf",pagecentre=T, width=15,height=12 ,paper = "special")
grid.arrange(xDense, blankPlot, scatterP, yDense, ncol=2, nrow=2, widths=c(4, 1.4), heights=c(1.4, 4))
dev.off()

########################
# DONE! -------------------------------------------------------------------
########################

# Contact me if you have any questions: https://osf.io/ujgs6/




